name: Deploy React Application to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the IP address of the GitHub runner
        id: get_ip
        run: |
          RUNNER_IP=$(curl -s https://api.ipify.org)  # Fetches the public IP of the GitHub runner
          echo "GitHub Runner IP: $RUNNER_IP"
          echo "::set-output name=runner_ip::$RUNNER_IP"  # Set the runner's IP as output

      - name: Check if the runner's IP matches the allowed IP
        run: |
          ALLOWED_IP="${{ secrets.ALLOWED_IP }}"  # This is the secret stored in GitHub that contains your public IP
          RUNNER_IP="${{ steps.get_ip.outputs.runner_ip }}"
          echo "Runner IP: $RUNNER_IP"

          if [[ "$RUNNER_IP" != "$ALLOWED_IP" ]]; then
            echo "Access Denied: Unauthorized IP address.";
            exit 1;  # Exit the workflow with error if IP doesn't match
          else
            echo "IP address is allowed. Proceeding with deployment.";
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Build the React app
        run: |
          npm run build

      - name: Setup SSH for EC2 Deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.EC2_PUBLIC_IP }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2 instance
        run: |
          # Rsync build files to EC2 instance
          rsync -avz --delete ./build/ ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/var/www/html/ # Adjust path if needed

          # Optionally restart server or run your start script
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'sudo systemctl restart ubuntu' # Example restart for Apache (adjust to your stack)
